#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

numlockx &

export GOPATH=$HOME"/workspace/go"
export GOROOT=$HOME"/go"
export PLAN9=/usr/local/plan9
export PATH=$PATH":"$GOPATH"/bin:"$GOROOT"/bin":$PLAN9"/bin"
export NASHROOT=$HOME/nashroot
export NASHPATH=$HOME/nash
export SHELL=$NASHROOT/bin/nash

exec rio -term st
