#!/bin/sh

set -o errexit
set -o nounset

hack/essentials.sh
hack/git.sh
hack/ssh.sh
hack/x.sh
hack/golang.sh
hack/window-managers.sh
hack/browsers.sh
hack/podman.sh
hack/zsh.sh
hack/vim.sh
hack/spotify.sh
