#!/bin/bash

set -o errexit
set -o nounset

workdir=$(mktemp -d)
outdir=iso
profiledir=archlive
mise_place_install="${profiledir}/airootfs/etc/skel/mise-en-place"

printf "workdir %s\n" "${workdir}"
printf "outdir %s\n" "${outdir}"

cp -r /usr/share/archiso/configs/releng "${profiledir}"
mkdir -p ${mise_place_install}
cp -r hack "${mise_place_install}"
cp bootstrap "${mise_place_install}"
cp pre-bootstrap "${mise_place_install}"

mkarchiso -v -w "${workdir}" -o "${outdir}" "${profiledir}"
