#!/bin/bash

set -o errexit
set -o nounset

outdir=iso
workdir=$(mktemp -d)
profilebasedir=$(mktemp -d)
profiledir="${profilebasedir}/releng"
pkgs_path="${profiledir}/packages.x86_64"
mise_place_install="${profiledir}/airootfs/etc/skel/mise-en-place"

printf "workdir %s\n" "${workdir}"
printf "profiledir %s\n" "${profiledir}"
printf "outdir %s\n" "${outdir}"

cp -r /usr/share/archiso/configs/releng "${profiledir}"
echo "netctl" >> "${pkgs_path}"
echo "dialog" >> "${pkgs_path}"
echo "wpa_supplicant" >> "${pkgs_path}"
echo "dhcpcd" >> "${pkgs_path}"

mkdir -p ${mise_place_install}
cp -r hack "${mise_place_install}"
cp bootstrap "${mise_place_install}"
cp pre-bootstrap "${mise_place_install}"

mkarchiso -v -w "${workdir}" -o "${outdir}" "${profiledir}"

rm -rf "${workdir}"
rm -rf "${profilebasedir}"
