#!/bin/bash

set -o errexit
set -o nounset

container="${1}"
severity="${2-}"

if [[ -z "${severity}" ]]; then
  severity=DEBUG
fi

printf "reading logs for container[%s] with severity >= [%s]\n" ${container} ${severity}
gcloud logging read "resource.labels.container_name=${container} AND severity>=${severity}" --format=json
